package me.vlink102.personal.overwatch.abilities;

public enum AbilityEnum {
    ANA_BIOTIC_RIFLE,
    ANA_BIOTIC_GRENADE,
    ANA_SLEEP_DART,
    ANA_NANO_BOOST,

    BAPTISTE_EXO_BOOTS,
    BAPTISTE_BIOTIC_LAUNCHER,
    BAPTISTE_BIOTIC_LAUNCHER_ALT_FIRE,
    BAPTISTE_REGENERATIVE_BURST,
    BAPTISTE_IMMORTALITY_FIELD,
    BAPTISTE_AMPLIFICATION_MATRIX,

    BRIGITTE_INSPIRE,
    BRIGITTE_ROCKET_FLAIL,
    BRIGITTE_REPAIR_PACK,
    BRIGITTE_WHIP_SHOT,
    BRIGITTE_BARRIER_SHIELD,
    BRIGITTE_RALLY,

    KIRIKO_WALL_CLIMB,
    KIRIKO_HEALING_OFUDA,
    KIRIKO_KUNAI,
    KIRIKO_SWIFT_STEP,
    KIRIKO_PROTECTION_SUZU,
    KIRIKO_KITSUNE_RUSH,

    LIFE_WEAVER_PARTING_GIFT,
    LIFE_WEAVER_HEALING_BLOSSOM,
    LIFE_WEAVER_THORN_VOLLEY,
    LIFE_WEAVER_PETAL_PLATFORM,
    LIFE_WEAVER_REJUVENATING_DASH,
    LIFE_WEAVER_LIFE_GRIP,
    LIFE_WEAVER_TREE_OF_LIFE,

    LUCIO_WALL_RIDE,
    LUCIO_SONIC_AMPLIFIER,
    LUCIO_SOUNDWAVE,
    LUCIO_CROSSFADE,
    LUCIO_AMP_IT_UP,
    LUCIO_SOUND_BARRIER,

    MERCY_SYMPATHETIC_RECOVERY,
    MERCY_ANGELIC_DESCENT,
    MERCY_CADUCEUS_STAFF,
    MERCY_CADUCEUS_BLASTER,
    MERCY_GUARDIAN_ANGEL,
    MERCY_RESURRECT,
    MERCY_VALKYRIE,

    MOIRA_BIOTIC_GRASP,
    MOIRA_BIOTIC_GRASP_ALT_FIRE,
    MOIRA_BIOTIC_ORB,
    MOIRA_FADE,
    MOIRA_COALESCENCE,

    ZENYATTA_SNAP_KICK,
    ZENYATTA_ORB_OF_DESTRUCTION,
    ZENYATTA_ORB_OF_DESTRUCTION_ALT_FIRE,
    ZENYATTA_ORB_OF_HARMONY,
    ZENYATTA_ORB_OF_DISCORD,
    ZENYATTA_TRANSCENDENCE
}
